name: Manual Angular Build

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment (test/prod)'
        required: true
        type: choice
        options:
          - TEST
          - PROD

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm install

    - name: Set API Key
      run: echo "API_KEY=${{ secrets[format('{0}_API_KEY', github.event.inputs.environment)] }}" >> $GITHUB_ENV

    - name: Build Angular app
      run: npm run build -- --configuration=${{ github.event.inputs.environment }}
      env:
        API_KEY: ${{ secrets[format('{0}_API_KEY', github.event.inputs.environment)] }}
